# bases:
# - ../../base

# patches:
# - replicas.yaml

# configMapGenerator:
# - name: mykustom-map
#   env: config.properties
bases:
- ../../base

patches:
- replicas.yaml

configMapGenerator:
- name: mykustom-map
  env: config.properties
